[project]
name = "forensic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SujithChristopher", email = "chrisbon95@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "tqdm>=4.70.0",
]

[project.scripts]
forensic = "forensic:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
